name: 'Terraform'

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - master
  push:
    branches:
     - master
    paths:
      - '*/**'
permissions:
  id-token: write
  contents: read 
env: 
  AWS_REGION: ap-south-1
  TF_VERSION: 1.2.6   

jobs:
  terraform:
    name: infrastructure-dev
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::434605749312:role/aws-deployment-tf
        role-session-name: staging-session    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }} 
          

    - name: Terraform Init, Format, Validate
      run: |
        terraform init
        terraform fmt -check
        terraform validate -no-color
      working-directory: terraform-infra
      
    - name: Install tfsec
      run: |
        wget -q $(wget -qO- https://api.github.com/repos/aquasecurity/tfsec/releases/latest | grep -o -E "https://[^\"]*linux_amd64.tar.gz") -O tfsec.tar.gz
        tar -xzf tfsec.tar.gz
        sudo install tfsec /usr/local/bin/

    - name: Run tfsec
      run: tfsec .
      working-directory: terraform-infra     
      continue-on-error: true
      
    - name: Install Checkov
      run: pip install checkov

    - name: Run Checkov PCI Scan
      run: |
        ls
        pwd
        checkov -d . --framework terraform --check PCI --download-external-modules true
      working-directory: terraform-infra
      continue-on-error: true
      


    - name: Terraform Plan
      run: terraform plan --var-file=dev.terraform.tfvars
      working-directory: terraform-infra


    # - name: Terraform Apply
    #   run: terraform apply --auto-approve --var-file=dev.terraform.tfvars 
